// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYvyW59qxaN4Vz_p-Dg_rz8O7vqpCyopU',
    appId: '1:768137611902:web:75af721f8a7a6229e3e62f',
    messagingSenderId: '768137611902',
    projectId: 'farmacia-app-123',
    authDomain: 'farmacia-app-123.firebaseapp.com',
    storageBucket: 'farmacia-app-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_IV92GUFk8bFJ_DWrFMwfIwSVmSkkvtA',
    appId: '1:768137611902:android:ef956c8f68c6ac51e3e62f',
    messagingSenderId: '768137611902',
    projectId: 'farmacia-app-123',
    storageBucket: 'farmacia-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAio3nSO4wUVWA06mX7MZngibBQjtIPMyM',
    appId: '1:768137611902:ios:c08f3c152f2bb10de3e62f',
    messagingSenderId: '768137611902',
    projectId: 'farmacia-app-123',
    storageBucket: 'farmacia-app-123.firebasestorage.app',
    iosBundleId: 'com.example.farmaciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAio3nSO4wUVWA06mX7MZngibBQjtIPMyM',
    appId: '1:768137611902:ios:c08f3c152f2bb10de3e62f',
    messagingSenderId: '768137611902',
    projectId: 'farmacia-app-123',
    storageBucket: 'farmacia-app-123.firebasestorage.app',
    iosBundleId: 'com.example.farmaciaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYvyW59qxaN4Vz_p-Dg_rz8O7vqpCyopU',
    appId: '1:768137611902:web:5dd6d6194d81a8f4e3e62f',
    messagingSenderId: '768137611902',
    projectId: 'farmacia-app-123',
    authDomain: 'farmacia-app-123.firebaseapp.com',
    storageBucket: 'farmacia-app-123.firebasestorage.app',
  );
}
